# The base image for the algorithm is required to be the PPS image.  That image will already have
# python and pip installed

# At this point we might want to install other libraries like the Algorithmia or DataRobot client libraries
ENV PATH=$PATH:/home/algo/.local/bin
