#!/bin/bash

set -e

cd /algorithmia
if [[ -f algorithm.zip ]]; then
  unzip -n algorithm.zip
elif [[ -d /algorithm ]]; then
  # For bind-mounting during development
  cp -rn /algorithm/. /algorithmia
fi

if [[ -x bin/pipe ]]; then
  exec /bin/langserver
else
  echo "Did not find executable /algorithmia/bin/pipe"
  exit 1
fi
