FROM algorithmiahq/langpack-builder:python2 as builder
COPY algosource /opt/algorithm
RUN /opt/algorithm/bin/build

FROM algorithmiahq/langpack-runner:python2
COPY --from=builder /home/algo/.local /home/algo/.local
COPY --from=builder /opt/algorithm/src /opt/algorithm/src
COPY --from=builder /opt/algorithm/algorithmia.conf /opt/algorithm/algorithmia.conf
