#!/bin/bash
set -e

CRAN_MIRROR=${CRAN_MIRROR:=http://cran.rstudio.com/}

# When installing from CRAN, use this mirror as a default
echo "options(repos=structure(c(CRAN=\"$CRAN_MIRROR\")))" > ~/.Rprofile

ROOTDIR=/opt/algorithm

# First install the latest CRAN packages system wide so it can populate the shared cache
python $ROOTDIR/rip.py --file $ROOTDIR/packages.txt --cran-latest --output-dependencies /tmp/cran-dependencies-1


# Copy the packages from the system wide location to our local dependencies directory
python $ROOTDIR/copy-cran-packages.py --lib /usr/local/lib/R/site-library --file /tmp/cran-dependencies-1 --destination `pwd`/dependencies

# Now when we install all other packages, we want them to go into the local dependencies directory
echo "R_LIBS_USER=$ROOTDIR/dependencies" > ~/.Renviron

# Re-run the package installation but only take non-latest CRAN packages
python $ROOTDIR/rip.py --file $ROOTDIR/packages.txt --skip-cran-latest --output-dependencies /tmp/cran-dependencies-2 --library `pwd`/dependencies

# Copy any dependencies from the system wide location to our local dependencies directory
python $ROOTDIR/copy-cran-packages.py --lib /usr/local/lib/R/site-library --file /tmp/cran-dependencies-2 --destination `pwd`/dependencies


