FROM {{base_image}}

# Set options that should be defined everywhere
ENV JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
ENV LANG C.UTF-8
LABEL langpacks_version={{langpacks_version}}

# Algo uid is set so that it is known for build caches, but the user id
# would presumably not be used already on our host (which seems better for security)
ENV ALGO_UID=2222
RUN adduser --disabled-password --gecos "" --uid $ALGO_UID algo

{% for package in packages %}
{% if package.script is not none %}
COPY {{package.script}} /tmp/{{package.script}}
RUN /tmp/{{package.script}}
{% endif %}
{% for line in package.dockerfile %}
{{line}}
{% endfor %}
{% endfor %}

# This is needed for compiled languages, otherwise we get permission errors everywhere
RUN mkdir /opt/algorithm
RUN chown $ALGO_UID:$ALGO_UID -R /opt/algorithm

USER $ALGO_UID

WORKDIR /opt/algorithm
