FROM {{base_image}}

# Set options that should be defined everywhere
ENV JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
ENV LANG C.UTF-8
ENV LANGPACKS_VERSION={{langpacks_version}}

# Algo uid is set so that it is known for build caches, but the user id
# would presumably not be used already on our host (which seems better for security)
RUN adduser --disabled-password --gecos "" --uid 2222 algo
COPY --from={{langserver_image}} /bin/init-langserver /bin/init-langserver
COPY --from={{langserver_image}} /langserver/target/release/langserver /bin/langserver

{% for package in packages %}
COPY {{package.script}} /tmp/{{package.script}}
RUN /tmp/{{package.script}}
{% for line in package.dockerfile %}
{{line}}
{% endfor %}
{% endfor %}

USER algo

WORKDIR /opt/algorithm
ENTRYPOINT /bin/init-langserver
