FROM {{builder_image}} as builder
USER 2222
COPY --chown=2222 algosource /opt/algorithm/
ENV HOME=/home/algo
RUN /opt/algorithm/bin/build

FROM {{runner_image}}
{% for artifact in config.artifacts %}
COPY --from=builder --chown=2222 {{artifact.source}} {{artifact.destination}}
{% endfor %}
USER 2222
WORKDIR /opt/algorithm
ENTRYPOINT /bin/init-langserver
