# Kaniko does not support copying from an absolute image name, see: https://github.com/GoogleContainerTools/kaniko/issues/297
FROM {{langserver_image}} AS langserver
FROM {{base_image}}

# Set options that should be defined everywhere
ENV JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
ENV LANG C.UTF-8
LABEL langpacks_version={{langpacks_version}}
LABEL langpacks_base_image={{base_image}}

# Algo uid is set so that it is known for build caches, but the user id
# would presumably not be used already on our host (which seems better for security)
RUN adduser --disabled-password --gecos "" --uid 2222 algo
COPY --from=langserver /bin/init-langserver /bin/init-langserver
COPY --from=langserver /langserver/target/release/langserver /bin/langserver

{% for package in packages %}
{% if package.script is not none %}
COPY {{package.script}} /tmp/{{package.script}}
RUN /tmp/{{package.script}}
{% endif %}
{% for line in package.dockerfile %}
{{line}}
{% endfor %}
{% endfor %}

USER algo

WORKDIR /opt/algorithm
ENTRYPOINT /bin/init-langserver
