FROM {{base_image}}

# Set options that should be defined everywhere
ENV JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
ENV LANG C.UTF-8
LABEL langpacks_version={{langpacks_version}}

# Algo uid is set so that it is known for build caches, but the user id
# would presumably not be used already on our host (which seems better for security)
RUN adduser --disabled-password --gecos "" --uid 2222 algo

{% for package in packages %}
COPY {{package.script}} /tmp/{{package.script}}
RUN /tmp/{{package.script}}
{% for line in package.dockerfile %}
{{line}}
{% endfor %}
{% endfor %}

USER algo

WORKDIR /opt/algorithm
