#!/bin/bash

set -e

CRAN_MIRROR=${CRAN_MIRROR:=http://cran.rstudio.com/}

# When installing from CRAN, use this mirror as a default
echo "options(repos=structure(c(CRAN=\"$CRAN_MIRROR\")))" > ~/.Rprofile

ROOTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

LOCBINDIR="/usr/local/bin"

# First install the latest CRAN packages system wide so it can populate the shared cache
python $LOCBINDIR/algorithmia-rip.py --file $ROOTDIR/packages.txt --cran-latest --output-dependencies /tmp/cran-dependencies-1

# Make the directory that will store all the packages necessary to run the algo
mkdir `pwd`/dependencies # If this directory already exists, weird things could happen

# Copy the packages from the system wide location to our local dependencies directory
python $LOCBINDIR/algorithmia-copy-cran-packages.py --lib /usr/local/lib/R/site-library --file /tmp/cran-dependencies-1 --destination `pwd`/dependencies

# Now when we install all other packages, we want them to go into the local dependencies directory
echo "R_LIBS_USER=`pwd`/dependencies" > ~/.Renviron

# Re-run the package installation but only take non-latest CRAN packages
python $LOCBINDIR/algorithmia-rip.py --file $ROOTDIR/packages.txt --skip-cran-latest --output-dependencies /tmp/cran-dependencies-2 --library `pwd`/dependencies

# Copy any dependencies from the system wide location to our local dependencies directory
python $LOCBINDIR/algorithmia-copy-cran-packages.py --lib /usr/local/lib/R/site-library --file /tmp/cran-dependencies-2 --destination `pwd`/dependencies
