FROM ubuntu:14.04

RUN DEBIAN_FRONTEND=noninteractive apt-get -y update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install \
    curl zip software-properties-common && \
    rm -rf /var/lib/apt/lists/* && \
    adduser --disabled-password --gecos "" algo


COPY ruby/template/bin/setup /tmp/ruby/setup
COPY python/template/bin/setup /tmp/python/setup
COPY javascript/template/bin/setup /tmp/javascript/setup
COPY rust/template/bin/setup /tmp/rust/setup
