FROM ubuntu:14.04

# additional auxillary packages for developers are on line 7
RUN DEBIAN_FRONTEND=noninteractive apt-get -y update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install \
    curl zip software-properties-common build-essential \
    imagemagick fontconfig fonts-wqy-microhei libopenblas-dev pandoc texlive && \
    rm -rf /var/lib/apt/lists/* && \
    adduser --disabled-password --gecos "" algo

WORKDIR /tmp/build
CMD ["bin/build"]

