COPY --chown=0:0 r36-buildtime/context/build /usr/local/bin/algorithmia-build
COPY --chown=0:0 r36-buildtime/context/rip.py /opt/algorithm/rip.py
COPY --chown=0:0 r36-buildtime/context/copy-cran-packages.py /opt/algorithm/copy-cran-packages.py
