[package]
name = "algorithmia-runner"
version = "0.1.0"
license = "MIT"
description = "Sample hello world algorithm"

[dependencies]
# libc = "0.2.0"
libloading = "*"
rustc-serialize = "*"

[dependencies.algorithmia]
version = "*"
#git = "https://github.com/anowell/algorithmia_rust.git"
