channels:
# Add your desired anaconda channels here
  - conda-forge
  - defaults
dependencies:
# Here are where your anaconda dependencies can be defined
  - pip:
# Add your pip dependencies (taken directly from pypi) here, we'll use the version of python and pip installed above
  - six>=1.12.0
  - algorithmia>=1.2,<2
