#!/bin/bash

DIRECTORY="$1"

set -eu

. /opt/conda/etc/profile.d/conda.sh

# The argument provided to this script ($1) denotes the path to locally installed solaris build path, which we use
# to update the anaconda environment.

cd $DIRECTORY
conda env update --prefix $ANACONDA_ENV --file=environment.yml
conda activate $ANACONDA_ENV
pip install .
chown algo:algo -R $ANACONDA_ENV
