#!/bin/bash

set -e

ROOTDIR=/opt/algorithm
# The argument provided to this script ($1) denotes the path to the yaml file which contains all of the necessary features
# to update the anaconda environment.


. /opt/conda/etc/profile.d/conda.sh
if [ -z "$1" ]; then
    conda env update --prefix "$ANACONDA_ENV" --file $ROOTDIR/requirements.yml;
else
    conda env update --prefix "$ANACONDA_ENV" --file "$1";
    chown algo:algo -R $ANACONDA_ENV;
fi
