#!/bin/bash

set -e

ROOTDIR=/opt/algorithm
CONDAENV=/tmp/conda_environment

# If additional components need to be compiled outside of the requirements.yml file, we recommend building a custom build file for that
# requirement.

conda env update --prefix $CONDAENV --file=$ROOTDIR/requirements.yaml -q
