[package]
name = "__ALGO__"
version = "0.0.1"

# Do NOT change the [[bin]] and [lib] sections
[[bin]]
name = "pipe"
path = "bin/pipe.rs"
[lib]
name = "algorithm"

[dependencies]
rustc-serialize = "0.3.18"
algorithmia = "1.0"
