[package]
name = "__ALGO__"
version = "0.1.0"

# The lib name is hard-coded into pipe.rs
[lib]
name = "algorithm"

[dependencies]
algorithmia = "2.0.0"
base64 = "0.3.0"
serde = "0.9.0"
serde_derive = "0.9.0"
serde_json = "0.9.0"
