[package]
name = "hello"
version = "0.1.0"
license = "MIT"
description = "Sample hello world algorithm"

# Do NOT change the [[bin]] and [lib] sections
[[bin]]
name = "pipe"
[lib]
name = "algorithm"


[dependencies]
rustc-serialize = "0.3.18"
algorithmia = "0.8.*"
