[package]
name = "__ALGO__"
version = "0.1.0"

# Do NOT change the [[bin]] and [lib] sections
[[bin]]
name = "pipe"
path = "bin/pipe.rs"
[lib]
name = "algorithm"

[dependencies]
rustc-serialize = "0.3.19"
algorithmia = "1.3.0"
